export const data = [
  {
    rank: "1",
    image: "https://companiesmarketcap.com/img/company-logos/64/WMT.webp",
    upperName: "Walmart",
    lowerName: "WMT",
    percentage: "$587.82 B",
    dollar: "$141.02",
    percentageGreen: "0.09%",
    country: "USA",
  },
  {
    rank: "2",
    image: "https://companiesmarketcap.com/img/company-logos/64/2222.SR.webp",
    upperName: "Saudi Aramco",
    lowerName: "2222.SR",
    percentage: "$496.88 B",
    dollar: "$9.23",
    percentageGreen: "1.14%",
    country: "S. Arabia",
  },
  {
    rank: "3",
    image: "https://companiesmarketcap.com/img/company-logos/64/AMZN.webp",
    upperName: "Amazon",
    lowerName: "AMZN",
    percentage: "$485.90 B",
    dollar: "$113.90",
    percentageGreen: "1.52%",
    country: "USA",
  },
  {
    rank: "4",
    image: "https://companiesmarketcap.com/img/company-logos/64/601857.SS.webp",
    upperName: "PetroChina",
    lowerName: "601857.SS",
    percentage: "$468.35 B",
    dollar: "$0.71",
    percentageGreen: "0.59%",
    country: "China",
  },
  {
    rank: "5",
    image: "https://companiesmarketcap.com/img/company-logos/64/600028.SS.webp",
    upperName: "Sinopec",
    lowerName: "600028.SS",
    percentage: "$463.18 B",
    dollar: "$0.59",
    percentageGreen: "1.18%",
    country: "China",
  },
  {
    rank: "6",
    image: "https://companiesmarketcap.com/img/company-logos/64/AAPL.webp",
    upperName: "Apple",
    lowerName: "AAPL",
    percentage: "$387.54 B",
    dollar: "$147.90",
    percentageGreen: "0.97%",
    country: "USA",
  },
  {
    rank: "7",
    image: "https://companiesmarketcap.com/img/company-logos/64/XOM.webp",
    upperName: "Exxon Mobil",
    lowerName: "XOM",
    percentage: "$352.19 B",
    dollar: "$108.55",
    percentageGreen: "1.31%",
    country: "USA",
  },
  {
    rank: "8",
    image: "https://companiesmarketcap.com/img/company-logos/64/SHEL.webp",
    upperName: "Shell",
    lowerName: "SHEL",
    percentage: "$329.58 B",
    dollar: "$56.67",
    percentageGreen: "6.30%",
    country: "UK",
  },
  {
    rank: "9",
    image: "https://companiesmarketcap.com/img/company-logos/64/UNH.webp",
    upperName: "UnitedHealth",
    lowerName: "UNH",
    percentage: "$313.13 B",
    dollar: "$544.53",
    percentageGreen: "0.25%",
    country: "USA",
  },
  {
    rank: "10",
    image: "https://companiesmarketcap.com/img/company-logos/64/601668.SS.webp",
    upperName: "China State Construction Engineering",
    lowerName: "601668.SS",
    percentage: "$311.23 B",
    dollar: "$0.68",
    percentageGreen: "0.61%",
    country: "China",
  },
];
