export const data = [
  {
    rank: "1",
    image: "https://companiesmarketcap.com/img/company-logos/64/WMT.webp",
    upperName: "Walmart",
    lowerName: "WMT",
    percentage: "2,300,000",
    dollar: "$141.00",
    percentageGreen: "0.10%",
    country: "USA",
  },
  {
    rank: "2",
    image: "https://companiesmarketcap.com/img/company-logos/64/AMZN.webp",
    upperName: "Amazon",
    lowerName: "AMZN",
    percentage: "1,523,000",
    dollar: "$114.01",
    percentageGreen: "1.43%",
    country: "USA",
  },
  {
    rank: "3",
    image: "https://companiesmarketcap.com/img/company-logos/64/2317.TW.webp",
    upperName: "Foxconn (Hon Hai Precision Industry)",
    lowerName: "2317.TW",
    percentage: "826,608",
    dollar: "$3.25",
    percentageGreen: "0.00%",
    country: "Taiwan",
  },
  {
    rank: "4",
    image: "https://companiesmarketcap.com/img/company-logos/64/ACN.webp",
    upperName: "Accenture",
    lowerName: "ACN",
    percentage: "721,000",
    dollar: "$282.70",
    percentageGreen: "1.01%",
    country: "Ireland",
  },
  {
    rank: "5",
    image: "https://companiesmarketcap.com/img/company-logos/64/VOW3.DE.webp",
    upperName: "Volkswagen",
    lowerName: "VOW3.DE",
    percentage: "668,294",
    dollar: "$131.77",
    percentageGreen: "0.15%",
    country: "Germany",
  },
  {
    rank: "6",
    image: "https://companiesmarketcap.com/img/company-logos/64/TCS.NS.webp",
    upperName: "Tata Consultancy Services",
    lowerName: "TCS.NS",
    percentage: "606,331",
    dollar: "$38.44",
    percentageGreen: "0.15%",
    country: "India",
  },
  {
    rank: "7",
    image: "https://companiesmarketcap.com/img/company-logos/64/DPW.DE.webp",
    upperName: "Deutsche Post",
    lowerName: "DPW.DE",
    percentage: "587,737",
    dollar: "$36.54",
    percentageGreen: "0.57%",
    country: "Germany",
  },
  {
    rank: "8",
    image: "https://companiesmarketcap.com/img/company-logos/64/UPS.webp",
    upperName: "United Parcel Service",
    lowerName: "UPS",
    percentage: "534,000",
    dollar: "$170.19",
    percentageGreen: "0.71%",
    country: "USA",
  },
  {
    rank: "9",
    image: "https://companiesmarketcap.com/img/company-logos/64/KR.webp",
    upperName: "Kroger",
    lowerName: "KR",
    percentage: "500,000",
    dollar: "$45.80",
    percentageGreen: "0.79%",
    country: "USA",
  },
  {
    rank: "10",
    image: "https://companiesmarketcap.com/img/company-logos/64/HD.webp",
    upperName: "Home Depot",
    lowerName: "HD",
    percentage: "500,000",
    dollar: "$292.50",
    percentageGreen: "0.81%",
    country: "USA",
  },
];
