export const data = [
  {
    rank: "1",
    image: "https://companiesmarketcap.com/img/company-logos/64/WMT.webp",
    upperName: "Walmart",
    lowerName: "WMT",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "2",
    image: "https://companiesmarketcap.com/img/company-logos/64/AMZN.webp",
    upperName: "Amazon",
    lowerName: "AMZN",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "3",
    image: "https://companiesmarketcap.com/img/company-logos/64/2317.TW.webp",
    upperName: "Foxconn (Hon Hai Precision Industry)",
    lowerName: "2317.TW",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "4",
    image: "https://companiesmarketcap.com/img/company-logos/64/ACN.webp",
    upperName: "Accenture",
    lowerName: "ACN",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "5",
    image: "https://companiesmarketcap.com/img/company-logos/64/VOW3.DE.webp",
    upperName: "Volkswagen",
    lowerName: "VOW3.DE",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "6",
    image: "https://companiesmarketcap.com/img/company-logos/64/TCS.NS.webp",
    upperName: "Tata Consultancy Services",
    lowerName: "TCS.NS",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "7",
    image: "https://companiesmarketcap.com/img/company-logos/64/DPW.DE.webp",
    upperName: "Deutsche Post",
    lowerName: "DPW.DE",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "8",
    image: "https://companiesmarketcap.com/img/company-logos/64/UPS.webp",
    upperName: "United Parcel Service",
    lowerName: "UPS",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "9",
    image: "https://companiesmarketcap.com/img/company-logos/64/KR.webp",
    upperName: "Kroger",
    lowerName: "KR",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "10",
    image: "https://companiesmarketcap.com/img/company-logos/64/HD.webp",
    upperName: "Home Depot",
    lowerName: "HD",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
];
