export const data = [
  {
    rank: "1",
    image: "https://companiesmarketcap.com/img/company-logos/64/SHLX.webp",
    upperName: "Shell Midstream Partners",
    lowerName: "SHLX",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "2",
    image: "https://companiesmarketcap.com/img/company-logos/64/CET.webp",
    upperName: "Central Securities",
    lowerName: "CET",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "3",
    image: "https://companiesmarketcap.com/img/company-logos/64/SOF.VI.webp",
    upperName: "Sofina",
    lowerName: "SOF.VI",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "4",
    image: "https://companiesmarketcap.com/img/company-logos/64/JSWHL.NS.webp",
    upperName: "JSW Holdings",
    lowerName: "JSWHL.NS",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "5",
    image: "https://companiesmarketcap.com/img/company-logos/64/ARG.AX.webp",
    upperName: "Argo Investments",
    lowerName: "ARG.AX",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "6",
    image:
      "https://companiesmarketcap.com/img/company-logos/64/BAJAJHLDNG.NS.webp",
    upperName: "Bajaj Holdings & Investment",
    lowerName: "BAJAJHLDNG.NS",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "7",
    image: "https://companiesmarketcap.com/img/company-logos/64/GBDC.webp",
    upperName: "Golub Capital",
    lowerName: "GBDC",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "8",
    image: "https://companiesmarketcap.com/img/company-logos/64/SOND.webp",
    upperName: "Sonder Holdings",
    lowerName: "SOND",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "9",
    image: "https://companiesmarketcap.com/img/company-logos/64/NLY.webp",
    upperName: "Annaly Capital Management",
    lowerName: "NLY",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "10",
    image: "https://companiesmarketcap.com/img/company-logos/64/HUDCO.NS.webp",
    upperName: "Hudco",
    lowerName: "HUDCO.NS",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
];
