export const data = [
  {
    rank: "1",
    image: "https://companiesmarketcap.com/img/company-logos/64/SHLX.webp",
    upperName: "Shell Midstream Partners",
    lowerName: "SHLX",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.06%",
    country: "USA",
  },
  {
    rank: "2",
    image: "https://companiesmarketcap.com/img/company-logos/64/CET.webp",
    upperName: "Central Securities",
    lowerName: "CET",
    percentage: "98.13%",
    dollar: "$36.15",
    percentageGreen: "0.36%",
    country: "USA",
  },
  {
    rank: "3",
    image: "https://companiesmarketcap.com/img/company-logos/64/SOF.VI.webp",
    upperName: "Sofina",
    lowerName: "SOF.VI",
    percentage: "97.77%",
    dollar: "$200.46",
    percentageGreen: "1.93%",
    country: "Belgium",
  },
  {
    rank: "4",
    image: "https://companiesmarketcap.com/img/company-logos/64/JSWHL.NS.webp",
    upperName: "JSW Holdings",
    lowerName: "JSWHL.NS",
    percentage: "96.90%",
    dollar: "$52.26",
    percentageGreen: "7.40%",
    country: "India",
  },
  {
    rank: "5",
    image: "https://companiesmarketcap.com/img/company-logos/64/ARG.AX.webp",
    upperName: "Argo Investments",
    lowerName: "ARG.AX",
    percentage: "96.82%",
    dollar: "$5.73",
    percentageGreen: "0.00%",
    country: "Australia",
  },
  {
    rank: "6",
    image:
      "https://companiesmarketcap.com/img/company-logos/64/BAJAJHLDNG.NS.webp",
    upperName: "Bajaj Holdings & Investment",
    lowerName: "BAJAJHLDNG.NS",
    percentage: "96.60%",
    dollar: "$80.06",
    percentageGreen: "1.27%",
    country: "India",
  },
  {
    rank: "7",
    image: "https://companiesmarketcap.com/img/company-logos/64/GBDC.webp",
    upperName: "Golub Capital",
    lowerName: "GBDC",
    percentage: "96.39%",
    dollar: "$13.02",
    percentageGreen: "0.57%",
    country: "USA",
  },
  {
    rank: "8",
    image: "https://companiesmarketcap.com/img/company-logos/64/SOND.webp",
    upperName: "Sonder Holdings",
    lowerName: "SOND",
    percentage: "96.36%",
    dollar: "$2.19",
    percentageGreen: "6.83%",
    country: "USA",
  },
  {
    rank: "9",
    image: "https://companiesmarketcap.com/img/company-logos/64/NLY.webp",
    upperName: "Annaly Capital Management",
    lowerName: "NLY",
    percentage: "96.30%",
    dollar: "$18.45",
    percentageGreen: "3.39%",
    country: "USA",
  },
  {
    rank: "10",
    image: "https://companiesmarketcap.com/img/company-logos/64/HUDCO.NS.webp",
    upperName: "Hudco",
    lowerName: "HUDCO.NS",
    percentage: "96.11%",
    dollar: "$0.44",
    percentageGreen: "1.53%",
    country: "India",
  },
];
