export const data = [
  {
    rank: "1",
    image: "https://companiesmarketcap.com/img/company-logos/64/2222.SR.webp",
    upperName: "Saudi Aramco",
    lowerName: "2222.SR",
    percentage: "$279.38 B",
    dollar: "$9.23",
    percentageGreen: "1.14%",
    country: " S. Arabia",
  },
  {
    rank: "2",
    image: "https://companiesmarketcap.com/img/company-logos/64/AAPL.webp",
    upperName: "Apple",
    lowerName: "AAPL",
    percentage: "$120.47 B",
    dollar: "$148.18",
    percentageGreen: "0.78%",
    country: "USA",
  },
  {
    rank: "3",

    image: "https://companiesmarketcap.com/img/company-logos/64/GOOG.webp",
    upperName: "Alphabet (Google)",
    lowerName: "GOOG",
    percentage: "$85.77 B",
    dollar: "$93.49",
    percentageGreen: "1.40%",
    country: "USA",
  },
  {
    rank: "4",
    image: "https://companiesmarketcap.com/img/company-logos/64/MSFT.webp",
    upperName: "Microsoft",
    lowerName: " MSFT",
    percentage: "$83.71 B",
    dollar: "$229.35",
    percentageGreen: "0.85%",
    country: "USA",
  },
  {
    rank: "5",
    image: "https://companiesmarketcap.com/img/company-logos/64/1398.HK.webp",
    upperName: "ICBC",
    lowerName: "1398.HK",
    percentage: "$65.91 B",
    dollar: "$0.46",
    percentageGreen: "0.00%",
    country: "China",
  },
  {
    rank: "6",
    image: "https://companiesmarketcap.com/img/company-logos/64/601939.SS.webp",
    upperName: "China Construction Bank",
    lowerName: "601939.SS",
    percentage: "$59.76 B",
    dollar: "$0.75",
    percentageGreen: "0.55%",
    country: "China",
  },
  {
    rank: "7",
    image: "https://companiesmarketcap.com/img/company-logos/64/EQNR.webp",
    upperName: "Equinor",
    lowerName: "EQNR",
    percentage: "$59.14 B",
    dollar: "$36.58",
    percentageGreen: "3.48%",
    country: "Norway",
  },
  {
    rank: "8",
    image: "https://companiesmarketcap.com/img/company-logos/64/XOM.webp",
    upperName: "Exxon Mobil",
    lowerName: "XOM",
    percentage: "$54.82 B",
    dollar: "$107.97",
    percentageGreen: "0.77%",
    country: "USA",
  },
  {
    rank: "9",
    image: "https://companiesmarketcap.com/img/company-logos/64/SHEL.webp",
    upperName: "Shell",
    lowerName: "SHEL",
    percentage: "$54.39 B",
    dollar: "$56.64",
    percentageGreen: "6.25%",
    country: "UK",
  },
  {
    rank: "10",
    image: "https://companiesmarketcap.com/img/company-logos/64/005930.KS.webp",
    upperName: "Samsung",
    lowerName: "005930.KS",
    percentage: "$49.40 B",
    dollar: "$41.94",
    percentageGreen: "0.17%",
    country: "S. Korea",
  },
];
