export const data = [
  {
    rank: "1",
    image: "https://companiesmarketcap.com/img/company-logos/64/2222.SR.webp",
    upperName: "Saudi Aramco",
    lowerName: "2222.SR",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "2",
    image: "https://companiesmarketcap.com/img/company-logos/64/AAPL.webp",
    upperName: "Apple",
    lowerName: "AAPL",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "3",

    image: "https://companiesmarketcap.com/img/company-logos/64/GOOG.webp",
    upperName: "Alphabet (Google)",
    lowerName: "GOOG",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "4",
    image: "https://companiesmarketcap.com/img/company-logos/64/MSFT.webp",
    upperName: "Microsoft",
    lowerName: " MSFT",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "5",
    image: "https://companiesmarketcap.com/img/company-logos/64/1398.HK.webp",
    upperName: "ICBC",
    lowerName: "1398.HK",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "6",
    image: "https://companiesmarketcap.com/img/company-logos/64/601939.SS.webp",
    upperName: "China Construction Bank",
    lowerName: "601939.SS",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "7",
    image: "https://companiesmarketcap.com/img/company-logos/64/EQNR.webp",
    upperName: "Equinor",
    lowerName: "EQNR",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "8",
    image: "https://companiesmarketcap.com/img/company-logos/64/XOM.webp",
    upperName: "Exxon Mobil",
    lowerName: "XOM",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "9",
    image: "https://companiesmarketcap.com/img/company-logos/64/SHEL.webp",
    upperName: "Shell",
    lowerName: "SHEL",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "10",
    image: "https://companiesmarketcap.com/img/company-logos/64/005930.KS.webp",
    upperName: "Samsung",
    lowerName: "005930.KS",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
];
