export const data = [
  {
    rank: "1",
    image: "https://companiesmarketcap.com/img/company-logos/64/HSZ.F.webp",
    upperName: "Sampoerna",
    lowerName: "HSZ.F",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "2",
    image: "https://companiesmarketcap.com/img/company-logos/64/UTY.F.webp",
    upperName: "United Tractors",
    lowerName: "UTY.F",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "3",
    image: "https://companiesmarketcap.com/img/company-logos/64/BYRA.F.webp",
    upperName: "Bank Rakyat Indonesia",
    lowerName: "BYRA.F",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "4",
    image: "https://companiesmarketcap.com/img/company-logos/64/E5F.F.webp",
    upperName: "XL Axiata",
    lowerName: "E5F.F",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "5",
    image: "https://companiesmarketcap.com/img/company-logos/64/SMS2.F.webp",
    upperName: "Semen Indonesia",
    lowerName: "SMS2.F",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "6",
    image: "https://companiesmarketcap.com/img/company-logos/64/D7V.F.webp",
    upperName: "Mayora",
    lowerName: "D7V.F",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "7",
    image: "https://companiesmarketcap.com/img/company-logos/64/OB8.F.webp",
    upperName: "Barito Pacific",
    lowerName: "OB8.F",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "8",
    image: "https://companiesmarketcap.com/img/company-logos/64/AV.L.webp",
    upperName: "Aviva",
    lowerName: "AV.L",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "9",
    image: "https://companiesmarketcap.com/img/company-logos/64/QLT.L.webp",
    upperName: "Quilter",
    lowerName: "QLT.L",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "10",
    image: "https://companiesmarketcap.com/img/company-logos/64/SYNT.L.webp",
    upperName: "Synthomer",
    lowerName: "SYNT.L",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
];
