export const data = [
  {
    rank: "1",
    image: "https://companiesmarketcap.com/img/company-logos/64/HSZ.F.webp",
    upperName: "Sampoerna",
    lowerName: "HSZ.F",
    percentage: "102,437.00%",
    dollar: "$0.06000",
    percentageGreen: "3.28%",
    country: "Indonesia",
  },
  {
    rank: "2",
    image: "https://companiesmarketcap.com/img/company-logos/64/UTY.F.webp",
    upperName: "United Tractors",
    lowerName: "UTY.F",
    percentage: "81,608.80%",
    dollar: "$2.05",
    percentageGreen: "1.92%",
    country: "Indonesia",
  },
  {
    rank: "3",
    image: "https://companiesmarketcap.com/img/company-logos/64/BYRA.F.webp",
    upperName: "Bank Rakyat Indonesia",
    lowerName: "BYRA.F",
    percentage: "62,664.10%",
    dollar: "$0.27",
    percentageGreen: "0.73%",
    country: "Indonesia",
  },
  {
    rank: "4",
    image: "https://companiesmarketcap.com/img/company-logos/64/E5F.F.webp",
    upperName: "XL Axiata",
    lowerName: "E5F.F",
    percentage: "38,091.80%",
    dollar: "$0.13",
    percentageGreen: "2.19%",
    country: "Indonesia",
  },
  {
    rank: "5",
    image: "https://companiesmarketcap.com/img/company-logos/64/SMS2.F.webp",
    upperName: "Semen Indonesia",
    lowerName: "SMS2.F",
    percentage: "34,922.50%",
    dollar: "$0.48",
    percentageGreen: "1.69%",
    country: "Indonesia",
  },
  {
    rank: "6",
    image: "https://companiesmarketcap.com/img/company-logos/64/D7V.F.webp",
    upperName: "Mayora",
    lowerName: "D7V.F",
    percentage: "13,593.50%",
    dollar: "$0.15",
    percentageGreen: "0.00%",
    country: "Indonesia",
  },
  {
    rank: "7",
    image: "https://companiesmarketcap.com/img/company-logos/64/OB8.F.webp",
    upperName: "Barito Pacific",
    lowerName: "OB8.F",
    percentage: "7,577.92%",
    dollar: "$0.04000",
    percentageGreen: "2.63%",
    country: "Indonesia",
  },
  {
    rank: "8",
    image: "https://companiesmarketcap.com/img/company-logos/64/AV.L.webp",
    upperName: "Aviva",
    lowerName: "AV.L",
    percentage: "3,117.08%",
    dollar: "$4.83",
    percentageGreen: "0.02%",
    country: "UK",
  },
  {
    rank: "9",
    image: "https://companiesmarketcap.com/img/company-logos/64/QLT.L.webp",
    upperName: "Quilter",
    lowerName: "QLT.L",
    percentage: "2,584.47%",
    dollar: "$1.12",
    percentageGreen: "0.39%",
    country: "UK",
  },
  {
    rank: "10",
    image: "https://companiesmarketcap.com/img/company-logos/64/SYNT.L.webp",
    upperName: "Synthomer",
    lowerName: "SYNT.L",
    percentage: "2,100.17%",
    dollar: "$1.37",
    percentageGreen: "2.16%",
    country: "UK",
  },
];
