export const data = [
  {
    rank: "1",
    image: "https://companiesmarketcap.com/img/company-logos/64/AAPL.webp",
    upperName: "Apple",
    lowerName: "AAPL",
    percentage: "$2.362 T",
    dollar: "$147.02",
    percentageGreen: "1.56%",
    country: "USA",
  },
  {
    rank: "2",
    image: "https://companiesmarketcap.com/img/company-logos/64/2222.SR.webp",
    upperName: "Saudi Aramco",
    lowerName: "2222.SR",
    percentage: "$2.030 T",
    dollar: "$9.23",
    percentageGreen: "1.14%",
    country: "S. Arabia",
  },
  {
    rank: "3",
    image: "https://companiesmarketcap.com/img/company-logos/64/MSFT.webp",
    upperName: "Microsoft",
    lowerName: " MSFT",
    percentage: "$1.701 T",
    dollar: "$228.13",
    percentageGreen: "1.38%",
    country: "USA",
  },
  {
    rank: "4",
    image: "https://companiesmarketcap.com/img/company-logos/64/AMZN.webp",
    upperName: "Amazon",
    lowerName: "AMZN",
    percentage: "$1.210 T",
    dollar: "$93.04",
    percentageGreen: "1.88%",
    country: "USA",
  },
  {
    rank: "5",
    image: "https://companiesmarketcap.com/img/company-logos/64/GOOG.webp",
    upperName: "Alphabet (Google)",
    lowerName: "GOOG",
    percentage: "$1.151 T",
    dollar: "$113.03",
    percentageGreen: "2.27%",
    country: "USA",
  },
  {
    rank: "6",
    image: "https://companiesmarketcap.com/img/company-logos/64/TSLA.webp",
    upperName: "Tesla",
    lowerName: "TSLA",
    percentage: "$702.68 B",
    dollar: "$225.87",
    percentageGreen: "0.55%",
    country: "USA",
  },
  {
    rank: "7",
    image: "https://companiesmarketcap.com/img/company-logos/64/BRK-B.webp",
    upperName: "Berkshire Hathaway",
    lowerName: "BRK-B",
    percentage: "$645.45 B",
    dollar: "$292.55",
    percentageGreen: "1.40%",
    country: "USA",
  },
  {
    rank: "8",
    image: "https://companiesmarketcap.com/img/company-logos/64/UNH.webp",
    upperName: "UnitedHealth",
    lowerName: "UNH",
    percentage: "$507.03 B",
    dollar: "$542.06",
    percentageGreen: "0.20%",
    country: "USA",
  },
  {
    rank: "9",
    image: "https://companiesmarketcap.com/img/company-logos/64/JNJ.webp",
    upperName: "Johnson & Johnson",
    lowerName: "JNJ",
    percentage: "$453.27 B",
    dollar: "$172.40",
    percentageGreen: "0.11%",
    country: "USA",
  },
  {
    rank: "10",
    image: "https://companiesmarketcap.com/img/company-logos/64/XOM.webp",
    upperName: "Exxon Mobil",
    lowerName: "XOM",
    percentage: "$451.29 B",
    dollar: "$108.29",
    percentageGreen: "1.07%",
    country: "USA",
  },
];
