export const data = [
  {
    rank: "1",
    image: "https://companiesmarketcap.com/img/company-logos/64/AAPL.webp",
    upperName: "Apple",
    lowerName: "AAPL",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "2",
    image: "https://companiesmarketcap.com/img/company-logos/64/2222.SR.webp",
    upperName: "Saudi Aramco",
    lowerName: "2222.SR",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "3",
    image: "https://companiesmarketcap.com/img/company-logos/64/MSFT.webp",
    upperName: "Microsoft",
    lowerName: " MSFT",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "4",
    image: "https://companiesmarketcap.com/img/company-logos/64/AMZN.webp",
    upperName: "Amazon",
    lowerName: "AMZN",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "5",
    image: "https://companiesmarketcap.com/img/company-logos/64/GOOG.webp",
    upperName: "Alphabet (Google)",
    lowerName: "GOOG",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "6",
    image: "https://companiesmarketcap.com/img/company-logos/64/TSLA.webp",
    upperName: "Tesla",
    lowerName: "TSLA",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "7",
    image: "https://companiesmarketcap.com/img/company-logos/64/BRK-B.webp",
    upperName: "Berkshire Hathaway",
    lowerName: "BRK-B",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "8",
    image: "https://companiesmarketcap.com/img/company-logos/64/UNH.webp",
    upperName: "UnitedHealth",
    lowerName: "UNH",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "9",
    image: "https://companiesmarketcap.com/img/company-logos/64/JNJ.webp",
    upperName: "Johnson & Johnson",
    lowerName: "JNJ",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "10",
    image: "https://companiesmarketcap.com/img/company-logos/64/XOM.webp",
    upperName: "Exxon Mobil",
    lowerName: "XOM",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
];
