export const data = [
  {
    rank: "1",
    image: "https://companiesmarketcap.com/img/company-logos/64/KXIN.webp",
    upperName: "Kaixin Auto",
    lowerName: "KXIN",
    percentage: "0.2393",
    dollar: "$0.55",
    percentageGreen: "1.87%",
    country: "China",
  },
  {
    rank: "2",
    image: "https://companiesmarketcap.com/img/company-logos/64/NM.webp",
    upperName: "Navios Maritime Holdings",
    lowerName: "NM",
    percentage: "0.2953",
    dollar: "$1.93",
    percentageGreen: "0.52%",
    country: "Monaco",
  },
  {
    rank: "3",
    image: "https://companiesmarketcap.com/img/company-logos/64/LTRPA.webp",
    upperName: "Liberty TripAdvisor Holdings",
    lowerName: "LTRPA",
    percentage: "0.3420",
    dollar: "$1.17",
    percentageGreen: "1.68%",
    country: "USA",
  },
  {
    rank: "4",
    image: "https://companiesmarketcap.com/img/company-logos/64/JUVE.MI.webp",
    upperName: "Juventus Turin",
    lowerName: "JUVE.MI",
    percentage: "0.3668",
    dollar: "$0.29",
    percentageGreen: "0.90%",
    country: "Italy",
  },
  {
    rank: "5",
    image: "https://companiesmarketcap.com/img/company-logos/64/DTEA.webp",
    upperName: "DAVIDsTEA",
    lowerName: "DTEA",
    percentage: "0.4389",
    dollar: "$0.89",
    percentageGreen: "1.64%",
    country: "Canada",
  },
  {
    rank: "6",
    image: "https://companiesmarketcap.com/img/company-logos/64/ZIM.webp",
    upperName: "ZIM Integrated Shipping Services",
    lowerName: "ZIM",
    percentage: "0.4658",
    dollar: "$23.87",
    percentageGreen: "1.89%",
    country: "Israel",
  },
  {
    rank: "7",
    image: "https://companiesmarketcap.com/img/company-logos/64/SBGI.webp",
    upperName: "Sinclair Broadcast",
    lowerName: "SBGI",
    percentage: "0.5376",
    dollar: "$18.99",
    percentageGreen: "2.98%",
    country: "USA",
  },
  {
    rank: "8",
    image: "https://companiesmarketcap.com/img/company-logos/64/LBTYB.webp",
    upperName: "Liberty Global",
    lowerName: "LBTYB",
    percentage: "0.5977",
    dollar: "$17.02",
    percentageGreen: "3.57%",
    country: "UK",
  },
  {
    rank: "9",
    image: "https://companiesmarketcap.com/img/company-logos/64/JXN.webp",
    upperName: "Jackson Financial",
    lowerName: "JXN",
    percentage: "0.6751",
    dollar: "$36.81",
    percentageGreen: "1.57%",
    country: "USA",
  },
  {
    rank: "10",
    image: "https://companiesmarketcap.com/img/company-logos/64/SOHU.webp",
    upperName: "Sohu.com",
    lowerName: "SOHU",
    percentage: "0.7005",
    dollar: "$14.93",
    percentageGreen: "0.73%",
    country: "China",
  },
];
