export const data = [
  {
    rank: "1",
    image: "https://companiesmarketcap.com/img/company-logos/64/KXIN.webp",
    upperName: "Kaixin Auto",
    lowerName: "KXIN",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "2",
    image: "https://companiesmarketcap.com/img/company-logos/64/NM.webp",
    upperName: "Navios Maritime Holdings",
    lowerName: "NM",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "3",
    image: "https://companiesmarketcap.com/img/company-logos/64/LTRPA.webp",
    upperName: "Liberty TripAdvisor Holdings",
    lowerName: "LTRPA",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "4",
    image: "https://companiesmarketcap.com/img/company-logos/64/JUVE.MI.webp",
    upperName: "Juventus Turin",
    lowerName: "JUVE.MI",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "5",
    image: "https://companiesmarketcap.com/img/company-logos/64/DTEA.webp",
    upperName: "DAVIDsTEA",
    lowerName: "DTEA",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "6",
    image: "https://companiesmarketcap.com/img/company-logos/64/ZIM.webp",
    upperName: "ZIM Integrated Shipping Services",
    lowerName: "ZIM",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "7",
    image: "https://companiesmarketcap.com/img/company-logos/64/SBGI.webp",
    upperName: "Sinclair Broadcast",
    lowerName: "SBGI",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "8",
    image: "https://companiesmarketcap.com/img/company-logos/64/LBTYB.webp",
    upperName: "Liberty Global",
    lowerName: "LBTYB",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "9",
    image: "https://companiesmarketcap.com/img/company-logos/64/JXN.webp",
    upperName: "Jackson Financial",
    lowerName: "JXN",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
  {
    rank: "10",
    image: "https://companiesmarketcap.com/img/company-logos/64/SOHU.webp",
    upperName: "Sohu.com",
    lowerName: "SOHU",
    percentage: "98.73%",
    dollar: "$15.82",
    percentageGreen: "0.00%",
    country: "USA",
  },
];
